CREATE TABLE `weekly_reportage` (
	`id` int AUTO_INCREMENT NOT NULL,
	`weekLabel` varchar(20) NOT NULL,
	`position` int NOT NULL DEFAULT 0,
	`sectionNumber` varchar(10) NOT NULL,
	`category` varchar(100) NOT NULL,
	`startupName` varchar(255) NOT NULL,
	`headline` varchar(500) NOT NULL,
	`subheadline` varchar(500),
	`bodyText` text NOT NULL,
	`quote` text,
	`feature1` varchar(500),
	`feature2` varchar(500),
	`feature3` varchar(500),
	`feature4` varchar(500),
	`stat1Value` varchar(50),
	`stat1Label` varchar(100),
	`stat2Value` varchar(50),
	`stat2Label` varchar(100),
	`stat3Value` varchar(50),
	`stat3Label` varchar(100),
	`ctaLabel` varchar(100),
	`ctaUrl` varchar(500),
	`websiteUrl` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `weekly_reportage_id` PRIMARY KEY(`id`)
);
